-- Add click_count to seasonal_experiences for popularity-based sorting.
-- Seeded with estimated popularity scores (0-100) based on global recognition.
ALTER TABLE seasonal_experiences
  ADD COLUMN IF NOT EXISTS click_count INTEGER NOT NULL DEFAULT 0;

-- Seed tier 1: globally iconic (90+)
UPDATE seasonal_experiences SET click_count = 95
WHERE name ILIKE '%Angkor Wat%'
   OR name ILIKE '%Northern Lights%'
   OR name ILIKE '%Aurora%'
   OR name ILIKE '%Oktoberfest%'
   OR name ILIKE '%Carnival%Rio%'
   OR name ILIKE '%Rio Carnival%'
   OR name ILIKE '%Cherry Blossom%'
   OR name ILIKE '%Hanami%'
   OR name ILIKE '%Machu Picchu%'
   OR name ILIKE '%Amalfi%'
   OR name ILIKE '%Santorini%'
   OR name ILIKE '%Sahara%'
   OR name ILIKE '%Bali%Rice%'
   OR name ILIKE '%Holi Festival%'
   OR name ILIKE '%Serengeti%'
   OR name ILIKE '%Great Migration%'
   OR name ILIKE '%Taj Mahal%'
   OR name ILIKE '%Mount Fuji%'
   OR name ILIKE '%Fuji%'
   OR name ILIKE '%Matterhorn%'
   OR name ILIKE '%Albuquerque%Balloon%';

-- Seed tier 2: world-famous treks, events, places (75-89)
UPDATE seasonal_experiences SET click_count = 82
WHERE click_count = 0
  AND (
       name ILIKE '%Everest%'
    OR name ILIKE '%Annapurna%'
    OR name ILIKE '%Patagonia%'
    OR name ILIKE '%Torres del Paine%'
    OR name ILIKE '%Inca Trail%'
    OR name ILIKE '%Camino%'
    OR name ILIKE '%Diwali%'
    OR name ILIKE '%Lantern Festival%'
    OR name ILIKE '%Carnival%Venice%'
    OR name ILIKE '%Venice%Carnival%'
    OR name ILIKE '%Running of the Bulls%'
    OR name ILIKE '%La Tomatina%'
    OR name ILIKE '%Burning Man%'
    OR name ILIKE '%Glastonbury%'
    OR name ILIKE '%Coachella%'
    OR name ILIKE '%Mardi Gras%'
    OR name ILIKE '%Day of the Dead%'
    OR name ILIKE '%Día de los Muertos%'
    OR name ILIKE '%Colosseum%'
    OR name ILIKE '%Acropolis%'
    OR name ILIKE '%Great Wall%'
    OR name ILIKE '%Ayers Rock%'
    OR name ILIKE '%Uluru%'
    OR name ILIKE '%Grand Canyon%'
    OR name ILIKE '%Yellowstone%'
    OR name ILIKE '%Iguazu%'
    OR name ILIKE '%Victoria Falls%'
    OR name ILIKE '%Dead Sea%'
    OR name ILIKE '%Petra%'
    OR name ILIKE '%Pompeii%'
    OR name ILIKE '%Dolomites%'
    OR name ILIKE '%Aoraki%'
    OR name ILIKE '%Milford%Track%'
    OR name ILIKE '%Abel Tasman%'
    OR name ILIKE '%Fiordland%'
    OR name ILIKE '%Phi Phi%'
    OR name ILIKE '%Maya Bay%'
    OR name ILIKE '%Maldives%'
    OR name ILIKE '%Seychelles%'
    OR name ILIKE '%Galápagos%'
    OR name ILIKE '%Galapagos%'
    OR name ILIKE '%Amazon%'
    OR name ILIKE '%Angel Falls%'
    OR name ILIKE '%Niagara%'
    OR name ILIKE '%Kyoto%'
    OR name ILIKE '%Tokyo%Tsukiji%'
    OR name ILIKE '%Shibuya%'
    OR name ILIKE '%Fushimi Inari%'
  );

-- Seed tier 3: well-known regional gems (55-74)
UPDATE seasonal_experiences SET click_count = 62
WHERE click_count = 0
  AND (
       name ILIKE '%Tuscany%'
    OR name ILIKE '%Cinque Terre%'
    OR name ILIKE '%Alberobello%'
    OR name ILIKE '%Aosta%'
    OR name ILIKE '%Alfama%'
    OR name ILIKE '%Sintra%'
    OR name ILIKE '%Blue Lagoon%'
    OR name ILIKE '%Reykjavik%'
    OR name ILIKE '%Edinburgh%'
    OR name ILIKE '%Scottish Highlands%'
    OR name ILIKE '%Cliffs of Moher%'
    OR name ILIKE '%Marrakech%'
    OR name ILIKE '%Chefchaouen%'
    OR name ILIKE '%Fez Medina%'
    OR name ILIKE '%Luang Prabang%'
    OR name ILIKE '%Ha Long Bay%'
    OR name ILIKE '%Hoi An%'
    OR name ILIKE '%Mekong%'
    OR name ILIKE '%Borobudur%'
    OR name ILIKE '%Ubud%'
    OR name ILIKE '%Komodo%'
    OR name ILIKE '%Zhangjiajie%'
    OR name ILIKE '%Guilin%'
    OR name ILIKE '%Banff%'
    OR name ILIKE '%Jasper%'
    OR name ILIKE '%Zion%'
    OR name ILIKE '%Bryce Canyon%'
    OR name ILIKE '%Antelope Canyon%'
    OR name ILIKE '%Yosemite%'
    OR name ILIKE '%Glacier%National%'
    OR name ILIKE '%Patagonia%'
    OR name ILIKE '%Cartagena%'
    OR name ILIKE '%Havana%'
    OR name ILIKE '%Kotor%'
    OR name ILIKE '%Dubrovnik%'
    OR name ILIKE '%Plitvice%'
    OR name ILIKE '%Lake Bled%'
    OR name ILIKE '%Hallstatt%'
    OR name ILIKE '%Rila%Monastery%'
    OR name ILIKE '%Transylvania%'
    OR name ILIKE '%Cappadocia%'
    OR name ILIKE '%Ephesus%'
    OR name ILIKE '%Pamukkale%'
    OR name ILIKE '%Wadi Rum%'
    OR name ILIKE '%Dead Sea%'
    OR name ILIKE '%Kerala%'
    OR name ILIKE '%Rajasthan%'
    OR name ILIKE '%Varanasi%'
    OR name ILIKE '%Jaipur%'
    OR name ILIKE '%Pushkar%'
    OR name ILIKE '%Hampi%'
    OR name ILIKE '%Sigiriya%'
    OR name ILIKE '%Ngorongoro%'
    OR name ILIKE '%Amboseli%'
    OR name ILIKE '%Okavango%'
    OR name ILIKE '%Cape Town%'
    OR name ILIKE '%Table Mountain%'
    OR name ILIKE '%Zanzibar%'
    OR name ILIKE '%Phuket%'
    OR name ILIKE '%Chiang Mai%'
    OR name ILIKE '%Pai%Canyon%'
    OR name ILIKE '%Bagan%'
    OR name ILIKE '%Inle Lake%'
    OR name ILIKE '%Chocolate Hills%'
    OR name ILIKE '%Palawan%'
    OR name ILIKE '%Tubbataha%'
    OR name ILIKE '%Halong%'
    OR name ILIKE '%Abel Tasman%'
    OR name ILIKE '%Queenstown%'
    OR name ILIKE '%Rotorua%'
    OR name ILIKE '%Franz Josef%'
    OR name ILIKE '%Whitsundays%'
    OR name ILIKE '%Ningaloo%'
    OR name ILIKE '%Great Barrier Reef%'
    OR name ILIKE '%Cradle Mountain%'
    OR name ILIKE '%Lofoten%'
    OR name ILIKE '%Svalbard%'
    OR name ILIKE '%Faroe Islands%'
    OR name ILIKE '%Azores%'
    OR name ILIKE '%Madeira%'
    OR name ILIKE '%Corsica%'
    OR name ILIKE '%Sardinia%'
  );

-- Seed tier 4: interesting but niche (30-54)
UPDATE seasonal_experiences SET click_count = 38
WHERE click_count = 0
  AND (
    country IN ('Japan', 'Italy', 'France', 'Spain', 'Portugal', 'Greece',
                'Thailand', 'Indonesia', 'Mexico', 'Peru', 'Colombia',
                'New Zealand', 'Australia', 'Iceland', 'Norway', 'Austria',
                'Switzerland', 'Morocco', 'India', 'Nepal', 'Sri Lanka')
  );

-- Default: everything else gets 10
UPDATE seasonal_experiences SET click_count = 10 WHERE click_count = 0;
