import { useState, useEffect } from 'react';
import Layout from '../components/Layout';
import { useAuth } from '../context/AuthContext';
import api from '../api/client';

export default function Settings() {
  const { user } = useAuth();
  const [displayName, setDisplayName] = useState(user?.displayName || '');
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState({ type: '', text: '' });

  // Photo source preference
  const [photoSource, setPhotoSource] = useState('unsplash'); // 'unsplash' | 'ai'

  useEffect(() => {
    // Load preference from localStorage (fast, no API call)
    const saved = localStorage.getItem('tt_photo_source');
    if (saved === 'ai' || saved === 'unsplash') setPhotoSource(saved);
  }, []);

  function handlePhotoSourceChange(value) {
    setPhotoSource(value);
    localStorage.setItem('tt_photo_source', value);
  }

  async function handleSubmit(e) {
    e.preventDefault();
    setLoading(true);
    setMessage({ type: '', text: '' });

    try {
      await api.put('/auth/me', { displayName });
      setMessage({ type: 'success', text: 'Profile updated successfully!' });
      window.location.reload();
    } catch (err) {
      setMessage({ type: 'error', text: err.message });
    } finally {
      setLoading(false);
    }
  }

  return (
    <Layout>
      <div className="page-header">
        <h1>Settings</h1>
        <p className="subtitle">Manage your profile</p>
      </div>

      <div className="settings-card">
        <h3>Profile Information</h3>

        {message.text && (
          <div className={`message ${message.type}`}>
            {message.text}
          </div>
        )}

        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label>Email</label>
            <input type="email" value={user?.email || ''} disabled />
            <span className="hint">Email cannot be changed</span>
          </div>

          <div className="form-group">
            <label>Username</label>
            <input type="text" value={user?.username || ''} disabled />
            <span className="hint">Username cannot be changed</span>
          </div>

          <div className="form-group">
            <label>Display Name</label>
            <input
              type="text"
              value={displayName}
              onChange={(e) => setDisplayName(e.target.value)}
              placeholder="Your display name"
              maxLength={100}
            />
          </div>

          <button type="submit" disabled={loading || !displayName.trim()}>
            {loading ? 'Saving...' : 'Save Changes'}
          </button>
        </form>
      </div>

      <div className="settings-card" style={{ marginTop: 24 }}>
        <h3>Cover Photos</h3>
        <p className="settings-desc">
          Choose the default source for cover photos on new pins.
          You can always switch per-pin using the buttons on each card.
        </p>

        <div className="settings-toggle-group">
          <label
            className={`settings-toggle-option${photoSource === 'unsplash' ? ' active' : ''}`}
            onClick={() => handlePhotoSourceChange('unsplash')}
          >
            <span className="settings-toggle-radio" />
            <div>
              <span className="settings-toggle-label">📷 Unsplash photos</span>
              <span className="settings-toggle-desc">Real travel photography from Unsplash</span>
            </div>
          </label>
          <label
            className={`settings-toggle-option${photoSource === 'ai' ? ' active' : ''}`}
            onClick={() => handlePhotoSourceChange('ai')}
          >
            <span className="settings-toggle-radio" />
            <div>
              <span className="settings-toggle-label">✦ AI illustrations</span>
              <span className="settings-toggle-desc">Stylized art generated by DALL-E</span>
            </div>
          </label>
        </div>
      </div>
    </Layout>
  );
}
